In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('clean_fx_data.csv')

In [3]:
data.head()

,date,eurusd,usdjpy,gbpusd,nzdusd,gbpjpy,eurgbp,eurcad,eursek,eurchf,...,usdhkd,usdsgd,usdinr,usdmxn,usdphp,usdidr,usdthb,usdmyr,usdzar,usdrub
0,2003-12-01,1.196501,109.169998,1.718597,0.644288,187.630005,0.6957,1.5596,9.0150,1.5525,...,7.7650,1.7217,45.709999,11.358,55.470001,8498.400391,39.889999,3.7968,6.3423,29.700001
1,2003-12-02,1.208897,108.730003,1.730313,0.646204,188.009995,0.6980,1.5670,9.0078,1.5562,...,7.7594,1.7200,45.629002,11.290,55.470001,8486.099609,39.848999,3.7971,6.2951,29.690001
2,2003-12-03,1.212298,108.300003,1.728101,0.649519,187.089996,0.7007,1.5759,8.9720,1.5579,...,7.7604,1.7161,45.549999,11.245,55.470001,8467.900391,39.806999,3.7902,6.1924,29.690001
3,2003-12-04,1.208094,108.269997,1.720697,0.645911,186.220001,0.7018,1.5829,8.9610,1.5560,...,7.7663,1.7135,45.548000,11.188,55.020000,8492.500000,39.869999,3.7987,6.3351,29.680000
4,2003-12-05,1.218695,107.620003,1.733102,0.645120,185.880005,0.7030,1.5876,8.9431,1.5504,...,7.7597,1.7140,45.449001,11.197,55.250000,8469.099609,39.813000,3.7896,6.2201,29.620001